#ifndef RESMANAGEMENTPANELHANDLERTYPES_H
#define RESMANAGEMENTPANELHANDLERTYPES_H

enum class ResManagementPanelHandlerType
{
	DirTree,
	FileList,
	Search,
};

#endif // RESMANAGEMENTPANELHANDLERTYPES_H
